# ============================
# Build & Publish
# ============================
[build]
  command = ""         # no build step (pure static)
  publish = "."        # index.html lives at repo root

# ============================
# Redirects
# ============================

# Keep your existing redirect (no trailing slash → with slash)
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

# Netlify CMS deep-link fix (so /admin/whatever loads)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# ---- Role-protected manuals (Netlify Identity) ----
# Allow logged-in users with role "guest" to fetch manuals
[[redirects]]
  from = "/manuals/*"
  to = "/manuals/:splat"
  status = 200
  conditions = { Role = ["guest"] }

# Block others: require login → send to guest portal
[[redirects]]
  from = "/manuals/*"
  to = "/guest.html"
  status = 401
  force = true

# ============================
# Headers
# ============================

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Keep HTML fresh
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Light security hardening
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

